providers = ["node"]

[phases.install]
cmd = "npm ci --only=production --no-audit --no-fund"

[phases.build]
cmd = "echo 'No build step needed for backend'"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[apt]
packages = ["chromium", "chromium-sandbox"]